# -*- coding: utf-8 -*-
"""TL ASSIGNMENT 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15OrK7Z_sPPKDr-or1gpLJJqKQgB1GcUd
"""



"""**ASSIGNMENT 2**

Building a python code. Assuming that we get temperature and humidity values and writing a condition to continually detect alarm in case of high temperature.
"""

import random
temp=random.randint(20,50) #getting random values for temperature
print("1.TEMPERATURE IS {} DEGREE CELCIUS".format(temp))
def temperature(temp):
  if(temp>=40):
      print("{} DEGREES IS HIGH TEMPERATURE!!- ALARM".format(temp))
  else:
      print("{} DEGREES IS NORMAL TEMPERATURE".format(temp))
temperature(temp)
humi=random.randint(30,65) #getting random values for temperature
print("2.HUMIDITY IS {}".format(humi))
def humidity(humi):
  if(humi>60):
      print("{}% HUMIDITY IS HIGH !!- ALARM".format(humi))
  else:
      print("{}% HUMIDITY IS NORMAL".format(humi))
humidity(humi)

